### ISSUE TITLE
Submits form when setting the value

### ISSUE THREAD

**Issue by markjritchie** [CuppaLabs/angular2-datetimepicker#4]
If you change the time or press done and the control is hosted in a form with a submit on the form the form will be submitted

**Comment by ibrahimiz** [comment]
Yes i encountered the same problem as well. If this is fixed, would be an apt one to use

**Comment by athir13en** [comment]
Hi, face the same problem when click on AM/PM toggle.

**Comment by studypro** [comment]
Hi, this issue is fixed or not? I am facing this problem.

**Comment by tolgatanriverdi** [comment]
I'm still facing this issue in the version we pulled from npm with using **npm install angular2-datetimepicker**

**Comment by patrickbard** [comment]
The issue persists
